export const OPEN_EDIT_PROFILE = 'OPEN_EDIT_PROFILE';

export const OPEN_EDIT_MEMBER = 'OPEN_EDIT_MEMBER';

export const CHANGE_CURRENT_TAP = 'CHANGE_CURRENT_TAP';

export const REDIRECT_SIDEBAR_TAP = 'REDIRECT_SIDEBAR_TAP';