// Common Type
export const API_LOADING = 'API_LOADING';
export const OPERATION_FAILED = 'OPERATION_FAILED';

export const OPEN_EDIT_PROFILE = 'OPEN_EDIT_PROFILE';
export const OPEN_EDIT_MEMBER = 'OPEN_EDIT_MEMBER';
export const CHANGE_CURRENT_TAP = 'CHANGE_CURRENT_TAP';
export const CHANGE_MESSAGE_PANEL_STATUS = 'CHANGE_MESSAGE_PANEL_STATUS';
export const CHANGE_SIGNUP_STEP = 'CHANGE_SIGNUP_STEP';
export const CHANGE_LOGGED_STATUS = 'CHANGE_LOGGED_STATUS';
export const CHANGE_SIDEBAR_STATUS = 'CHANGE_SIDEBAR_STATUS';

// job page
export const GET_JOB_LIST_SUCCESS = 'GET_JOB_LIST_SUCCESS';
export const POST_JOB_SUCCESS = 'POST_JOB_SUCCESS';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';


export const CHANGE_SEARCH_COMPANY = 'CHANGE_SEARCH_COMPANY';
export const CHANGE_SEARCH_JOB = 'CHANGE_SEARCH_JOB';
export const CHANGE_SEARCH_CANDIDATE = 'CHANGE_SEARCH_CANDIDATE';
export const CHANGE_SEARCH_APPLIED = 'CHANGE_SEARCH_APPLIED';
export const CHANGE_SEARCH_DATE = 'CHANGE_SEARCH_DATE'; 

//Profile page 
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_MEMBER_SUCCESS = 'EDIT_MEMBER_SUCCESS';

//Message Page
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const SHOW_MESSAGE_DETAIL_SUCCESS = 'SHOW_MESSAGE_DETAIL_SUCCESS';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';

//Auth

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SEND_VERIFICATION_SUCCESS = 'SEND_VERIFICATION_SUCCESS'
export const USER_VERIFICATION_SUCCESS = 'USER_VERIFICATION_SUCCESS'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'