export const OPEN_EDIT_PROFILE = 'OPEN_EDIT_PROFILE';

export const OPEN_EDIT_MEMBER = 'OPEN_EDIT_MEMBER';

export const CHANGE_CURRENT_TAP = 'CHANGE_CURRENT_TAP';

export const CHANGE_MESSAGE_PANEL_STATUS = 'CHANGE_MESSAGE_PANEL_STATUS';

export const CHANGE_SIGNUP_STEP = 'CHANGE_SIGNUP_STEP';

export const CHANGE_LOGGED_STATUS = 'CHANGE_LOGGED_STATUS';

export const CHANGE_SIDEBAR_STATUS = 'CHANGE_SIDEBAR_STATUS';